"""
Agent Logic Module: Implements the core ReAct (Reasoning and Acting) framework.
This module is shared between the MCP Host and the MCP Server to provide
consistent reasoning capabilities for both top-level and recursive sub-tasks.
"""

import re
import json
import inspect
from typing import List, Dict, Any, Optional, Callable, Awaitable
from config import get_genai_client, MODEL_ID, setup_logger

logger = setup_logger("AgentLogic")

# The standard ReAct prompt template that enforces structured thinking.
SYSTEM_PROMPT_TEMPLATE = """
You are a helpful AI assistant. You solve problems by following a structured ReAct (Reasoning and Acting) loop.
You have access to the following tools:

{tool_definitions}

You MUST follow this exact format for every turn:

Thought: [Your reasoning about what to do next]
Action: [The name of the tool to use]
Action Input: [The JSON arguments for the tool]
Observation: [The result of the tool - THIS WILL BE PROVIDED TO YOU]

... (repeat Thought/Action/Action Input/Observation if needed)

Final Answer: [Your final response to the user, addressing their ORIGINAL query comprehensively]

Important: 
1. Only provide ONE Thought/Action/Action Input per turn. 
2. Wait for the Observation before continuing.
3. If you have enough information, provide the Final Answer immediately.
4. Efficiency Rule: Prioritize '[Self-Resolving]' tools. If a tool can find its own missing data, call it directly.
"""

class SubAgent:
    """
    A lightweight recursive agent that tools can use to solve sub-goals.
    
    This class is injected into 'Smart Tools' as the 'sub_agent' parameter,
    allowing them to perform autonomous discovery (e.g., finding location)
    without hardcoding specific tool dependencies.
    """
    def __init__(self, registry: Any, model_id: str, depth: int, execute_func: Callable[[str, Dict[str, Any]], Awaitable[str]]):
        self.registry = registry
        self.model_id = model_id
        self.depth = depth
        self.execute_func = execute_func # The bridge to the execution environment (local or MCP)

    async def solve(self, goal: str) -> str:
        """Runs a nested ReAct loop to solve a specific natural language sub-goal."""
        logger.debug(f"    [Sub-Agent (Depth {self.depth})] Goal: {goal}")
        agent = GenericReActAgent(self.registry, self.execute_func, self.model_id, depth=self.depth)
        return await agent.run(goal)

class GenericReActAgent:
    """
    The primary engine for the ReAct loop. 
    Can operate as a top-level Host agent or a nested Sub-Agent.
    """
    def __init__(self, registry: Any, execute_func: Callable[[str, Dict[str, Any]], Awaitable[str]], model_id: str = MODEL_ID, depth: int = 0):
        self.client = get_genai_client()
        self.model_id = model_id
        self.registry = registry # Registry must support get_relevant_tools(query)
        self.execute_func = execute_func # Strategy for tool execution (e.g., session.call_tool)
        self.depth = depth
        self.chat_history = [] # Stores final User/Assistant turns for context
        
    def _format_docs(self, tools: List[Dict[str, Any]]) -> str:
        """Formats tool metadata for inclusion in the system prompt."""
        docs = []
        for t in tools:
            sig = t.get("signature", "") or ""
            # Tag self-resolving tools to guide the LLM's planning
            capability = " [Self-Resolving]" if "sub_agent" in sig else ""
            docs.append(f"- {t.get('full_doc', t.get('name'))}{capability}")
        return "\n".join(docs)

    async def run(self, user_input: str) -> str:
        """
        Executes the ReAct loop for a given user input.
        Returns the 'Final Answer' generated by the model.
        """
        # 1. Dynamically retrieve tools relevant to this specific task (Tool-RAG)
        relevant_tools = await self.registry.get_relevant_tools(user_input)
        tool_docs = self._format_docs(relevant_tools)
        
        # 2. Track intermediate steps for the current reasoning chain
        task_history = [f"User: {user_input}"]
        indent = "  " * self.depth

        for i in range(8): # Max steps to prevent infinite reasoning
            # Combine long-term chat history with current task steps
            full_context = self.chat_history + task_history
            prompt = (SYSTEM_PROMPT_TEMPLATE.format(tool_definitions=tool_docs) + 
                      "\n\n" + "\n".join(full_context) + "\nThought:")
            
            # Generate the next step in the reasoning chain
            response = self.client.models.generate_content(model=self.model_id, contents=prompt)
            raw_output = "Thought: " + response.text.strip()
            # LOG AS DEBUG: CLUTTER REDUCTION
            logger.debug(f"\n{indent}--- Step {i+1} (Depth {self.depth}) ---\n{indent}{raw_output}")
            
            # If the model has reached a conclusion, store and return it
            if "Final Answer:" in raw_output:
                final_answer = raw_output.split("Final Answer:")[-1].strip()
                if self.depth == 0:
                    self.chat_history.append(f"User: {user_input}")
                    self.chat_history.append(f"Assistant: {final_answer}")
                return final_answer
            
            # Parse the Action and Action Input from the model's response
            try:
                action_match = re.search(r"Action:\s*(\w+)", raw_output)
                input_match = re.search(r"Action Input:\s*({.*})", raw_output, re.DOTALL)
                
                if not action_match or not input_match:
                    raise ValueError("Incomplete Action/Action Input format.")
                
                action_name = action_match.group(1).strip()
                action_args = json.loads(input_match.group(1).strip())
                
                # Execute the tool via the provided callback (e.g., MCP Stdio call)
                observation = await self.execute_func(action_name, action_args)
                
                task_history.append(raw_output)
                task_history.append(f"Observation: {observation}")
                # LOG AS DEBUG: CLUTTER REDUCTION
                logger.debug(f"{indent}Observation: {observation}")
                
            except Exception as e:
                obs = f"Error: {str(e)}"
                task_history.append(raw_output)
                task_history.append(f"Observation: {obs}")
                logger.error(f"{indent}Execution Error: {obs}")

        return "Max reasoning steps reached."
